# Generated by Django 5.1.7 on 2026-09-25 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('label', models.CharField(max_length=16)),
                ('diabetic_risk', models.CharField(max_length=16)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='products.product')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
