# Generated by Django 5.1.7 on 2026-09-25 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('off', 'Open Food Facts'), ('community', 'Community submission')], default='off', max_length=16)),
                ('calories_kcal', models.FloatField(blank=True, null=True)),
                ('sugar_g', models.FloatField(blank=True, null=True)),
                ('saturated_fat_g', models.FloatField(blank=True, null=True)),
                ('sodium_mg', models.FloatField(blank=True, null=True)),
                ('carbohydrates_g', models.FloatField(blank=True, null=True)),
                ('fiber_g', models.FloatField(blank=True, null=True)),
                ('protein_g', models.FloatField(blank=True, null=True)),
                ('ingredients_text', models.TextField(blank=True)),
                ('additives', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('nutrition_payload', models.JSONField(default=dict)),
                ('ingredients_text', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CachedExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('label', models.CharField(max_length=16)),
                ('diabetic_risk', models.CharField(max_length=16)),
                ('explanation_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='products.product')),
            ],
        ),
    ]
